version: '3'

networks:
  laravel-plain:

services:
  site-plain:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: nginx-plain
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php-plain
      - composer-plain
    networks:
      - laravel-plain

  php-plain:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: php-plain
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - laravel-plain

  composer-plain:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: composer-plain
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php-plain
    user: laravel
    entrypoint: ['composer', '--ignore-platform-reqs']
    networks:
      - laravel-plain